version: "3.9"
services:
  chatgpt-next-web:
    build: .
    expose:
      - 3000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - DISABLE_GPT4=$DISABLE_GPT4
      - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
      - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
      - OPENAI_SB=$OPENAI_SB
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatgpt-next-web.entrypoints=websecure"
      - "traefik.http.routers.chatgpt-next-web.tls.certResolver=letsencrypt"
      - "traefik.http.routers.chatgpt-next-web.rule=Host(`chat.raku.vcorp.ai`)"
      - "traefik.http.services.chatgpt-next-web.loadbalancer.server.port=3000" 

networks:
  dokploy-network:
    external: true

  # chatgpt-next-web-proxy:
  #   profiles: [ "proxy" ]
  #   container_name: chatgpt-next-web-proxy
  #   build: .  # 使用当前目录的 Dockerfile 构建镜像
  #   image: chatgpt-next-web:local  # 为本地构建的镜像指定名称和标签
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - OPENAI_API_KEY=$OPENAI_API_KEY
  #     - GOOGLE_API_KEY=$GOOGLE_API_KEY
  #     - CODE=$CODE
  #     - PROXY_URL=$PROXY_URL
  #     - BASE_URL=$BASE_URL
  #     - OPENAI_ORG_ID=$OPENAI_ORG_ID
  #     - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
  #     - DISABLE_GPT4=$DISABLE_GPT4
  #     - ENABLE_BALANCE_QUERY=$ENABLE_BALANCE_QUERY
  #     - DISABLE_FAST_LINK=$DISABLE_FAST_LINK
  #     - OPENAI_SB=$OPENAI_SB
